# Generated by Django 5.2.8 on 2025-11-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="recipes.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "unit_of_measurement",
                    models.CharField(
                        choices=[
                            ("CUPS", "cups"),
                            ("TEASPOONS", "tsps"),
                            ("TABLESPOONS", "tbsps"),
                            ("MILLILITERS", "ml"),
                            ("LITERS", "l"),
                            ("FLUID_OUNCES", "fl oz"),
                            ("PINTS", "pt"),
                            ("QUARTS", "qt"),
                            ("GALLONS", "gal"),
                            ("GRAMS", "g"),
                            ("KILOGRAMS", "kg"),
                            ("OUNCES", "oz"),
                            ("POUNDS", "lb"),
                            ("UNITS", "units"),
                            ("PIECES", "pcs"),
                            ("SLICES", "slices"),
                            ("CLOVES", "cloves"),
                            ("CAN", "can"),
                            ("BUNCH", "bunch"),
                            ("PINCH", "pinch"),
                            ("DASH", "dash"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True)),
                ("body", models.TextField(max_length=500)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("recipe", "order")},
            },
        ),
    ]
